version: '2'
services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
  web:
    build: .
    ports:
      - "8080:80"
    environment:
      - POSTGRESQL_INSTANCE_NAME=postgres
      - POSTGRESQL_USERNAME=postgres    # suit the username in your db service env, defualt: postgres
      - POSTGRESQL_PASSWORD= # suit the password in your db service env, defualt: _ (blank)
      - POSTGRESQL_PORT_5432_TCP_ADDR=postgres   # your db service name is the linked db container tcp address
      - POSTGRESQL_PORT_5432_TCP_PORT=5432
    depends_on:
      - postgres  # won't work if postgres set up slowly so better your web sleep for a while
    volumes:
      - .:/www # be sure to let entrypoint.sh executable