web:
  build: .
  ports:
    - "8080:80"
  environment:
    - POSTGRESQL_INSTANCE_NAME=postgres
    - POSTGRESQL_USERNAME=postgres
    - POSTGRESQL_PASSWORD=
  links:
    - postgres:postgresql

postgres:
  image: daocloud.io/postgres:latest
  environment:
    - POSTGRESQL_INSTANCE_NAME=postgres
    - POSTGRESQL_USER=postgres
    - POSTGRESQL_PASSWORD=
  ports:
    - "5432:5432"