version: '2'
services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
  web:
    build: .
    ports:
      - "8080:80"
    environment:
      - POSTGRESQL_INSTANCE_NAME=postgres
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=
      - POSTGRESQL_PORT_5432_TCP_ADDR=postgres
      - POSTGRESQL_PORT_5432_TCP_PORT=5432
    depends_on:
      - postgres