# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-06 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('rango', '0002_auto_20160806_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
